# Generated by Django 3.2.25 on 2026-01-28 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=250)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('announcement_id', models.AutoField(primary_key=True, serialize=False)),
                ('announcement_title', models.CharField(max_length=200)),
                ('announcement_desc', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='announcements_folder/')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('term_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(default='unknown', max_length=150)),
                ('university_id', models.CharField(default='0000', max_length=50, unique=True)),
                ('email', models.EmailField(default='unknown@example.com', max_length=254, unique=True)),
                ('password', models.CharField(default='password', max_length=250)),
                ('role', models.CharField(default='student', max_length=50)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Violations',
            fields=[
                ('violation_id', models.AutoField(primary_key=True, serialize=False)),
                ('violation_type', models.TextField()),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Violation_User',
            fields=[
                ('violation_user_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
                ('violation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.violations')),
            ],
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('researcher_id', models.AutoField(primary_key=True, serialize=False)),
                ('bio_description', models.TextField(blank=True)),
                ('OCRID', models.CharField(blank=True, max_length=50)),
                ('google_scholar_id', models.CharField(blank=True, max_length=50)),
                ('publications', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
