# Generated by Django 3.2.25 on 2026-02-01 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammeCoordinator',
            fields=[
                ('prog_coor_id', models.AutoField(primary_key=True, serialize=False)),
                ('faculty_id', models.CharField(max_length=50)),
                ('prog_name', models.CharField(max_length=150)),
                ('faculty', models.CharField(max_length=150)),
            ],
        ),
        migrations.RenameField(
            model_name='researcher',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(blank=True, default='unknown', max_length=150),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('program_of_studies', models.CharField(max_length=150)),
                ('year_of_studies', models.CharField(max_length=20)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchPaper',
            fields=[
                ('paper_id', models.AutoField(primary_key=True, serialize=False)),
                ('paper_title', models.CharField(max_length=250)),
                ('paper_category', models.CharField(max_length=100)),
                ('paper_desc', models.TextField()),
                ('paper_doi', models.CharField(blank=True, max_length=100, verbose_name='DOI')),
                ('paper_pdf', models.FileField(upload_to='research_papers/')),
                ('paper_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='Pending', max_length=20)),
                ('total_bookmarked', models.IntegerField(default=0)),
                ('total_likes', models.IntegerField(default=0)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('prog_coor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.programmecoordinator')),
                ('researcher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.researcher')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notify_id', models.AutoField(primary_key=True, serialize=False)),
                ('notify_title', models.CharField(max_length=100)),
                ('notify_message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paper_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.researchpaper')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('message_desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.admin')),
                ('paper_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myapp.researchpaper')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='CoAuthor',
            fields=[
                ('coauth_id', models.AutoField(primary_key=True, serialize=False)),
                ('paper_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_authors', to='myapp.researchpaper')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
