# Generated by Django 6.0.2 on 2026-02-05 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20260202_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmecoordinator',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='paper_coauthor',
            field=models.ManyToManyField(blank=True, related_name='coauthored_papers', to='myapp.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='programmecoordinator',
            name='faculty',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='programmecoordinator',
            name='faculty_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='programmecoordinator',
            name='prog_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='Bookmarks',
            fields=[
                ('bookmark_id', models.AutoField(primary_key=True, serialize=False)),
                ('bookmarked_at', models.DateTimeField(auto_now_add=True)),
                ('paper_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.researchpaper')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('like_id', models.AutoField(primary_key=True, serialize=False)),
                ('liked_at', models.DateTimeField(auto_now_add=True)),
                ('paper_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.researchpaper')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('submission_id', models.AutoField(primary_key=True, serialize=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='under review', max_length=50)),
                ('paper_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.researchpaper')),
            ],
        ),
        migrations.DeleteModel(
            name='Violation_User',
        ),
    ]
