# Generated by Django 3.2.25 on 2026-02-02 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmarks',
            fields=[
                ('bookmark_id', models.AutoField(primary_key=True, serialize=False)),
                ('bookmarked_at', models.DateTimeField(auto_now_add=True)),
                ('paper_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.researchpaper')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('like_id', models.AutoField(primary_key=True, serialize=False)),
                ('liked_at', models.DateTimeField(auto_now_add=True)),
                ('paper_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.researchpaper')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('submission_id', models.AutoField(primary_key=True, serialize=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='under review', max_length=50)),
                ('paper_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.researchpaper')),
            ],
        ),
        migrations.DeleteModel(
            name='Violation_User',
        ),
    ]
