# Generated by Django 6.0.1 on 2026-01-11 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_researcher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researcher',
            old_name='user_id',
            new_name='user',
        ),
    ]
