# Generated by Django 6.0.2 on 2026-02-05 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_reports'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reports',
        ),
    ]
