# Generated by Django 3.2.25 on 2026-02-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20260202_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchpaper',
            name='paper_coauthor',
            field=models.ManyToManyField(blank=True, related_name='coauthored_papers', to='myapp.User'),
        ),
    ]
