# Generated by Django 6.0.1 on 2026-01-11 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_user_id_researcher_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='OCRID',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='researcher',
            name='bio_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='researcher',
            name='google_scholar_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='researcher',
            name='publications',
            field=models.TextField(blank=True),
        ),
    ]
