# Generated by Django 6.0.2 on 2026-02-05 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_delete_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='violations',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.comment'),
        ),
        migrations.AddField(
            model_name='violations',
            name='reporter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violations_filed', to='myapp.user'),
        ),
        migrations.AlterField(
            model_name='violations',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations_received', to='myapp.user'),
        ),
    ]
