# Generated by Django 6.0.2 on 2026-02-05 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_violations_comment_violations_reporter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='paper_id',
        ),
    ]
