# Generated by Django 6.0.1 on 2026-02-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_programmecoordinator_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmecoordinator',
            name='test_field',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
