# Generated by Django 6.0.1 on 2026-02-04 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_programmecoordinator_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmecoordinator',
            name='test_field',
        ),
    ]
