# Generated by Django 3.2.25 on 2026-01-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_announcements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='announcements_folder/'),
        ),
    ]
