# Generated by Django 6.0.1 on 2026-02-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_programmecoordinator_test_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmecoordinator',
            name='faculty',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='programmecoordinator',
            name='faculty_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='programmecoordinator',
            name='prog_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
