# Generated by Django 6.0.2 on 2026-02-06 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_notification_sender_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='sender_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
        ),
    ]
