# Generated by Django 6.0.2 on 2026-02-06 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_notification_sender_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchpaper',
            name='student_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.student'),
        ),
        migrations.AlterField(
            model_name='researchpaper',
            name='researcher_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.researcher'),
        ),
    ]
