# Generated by Django 6.0.1 on 2026-02-04 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_programmecoordinator_faculty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmecoordinator',
            name='user_id',
        ),
    ]
