# Generated by Django 6.0.2 on 2026-02-12 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_researchpaper_student_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchpaper',
            name='paper_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revision', 'Revision')], default='Pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='CoAuthor',
        ),
    ]
