# Generated by Django 6.0.1 on 2026-02-04 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_programmecoordinator_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmecoordinator',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
            preserve_default=False,
        ),
    ]
