# Generated by Django 6.0.2 on 2026-02-13 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_researchpaper_paper_status_delete_coauthor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='program_of_studies',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_of_studies',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
