# Generated by Django 6.0.1 on 2026-02-04 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_programmecoordinator_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmecoordinator',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
        ),
    ]
