# Generated by Django 6.0.2 on 2026-04-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_user_is_banned_alter_researchpaper_paper_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='program_of_studies',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_of_studies',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
