# Generated by Django 6.0.2 on 2026-04-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_student_program_of_studies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchpaper',
            name='paper_cover',
            field=models.ImageField(blank=True, null=True, upload_to='research_papers/'),
        ),
    ]
