# Generated by Django 6.0.2 on 2026-04-22 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_researchpaper_paper_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchpaper',
            name='paper_cover',
        ),
    ]
